# Generated by Django 5.0.3 on 2024-03-23 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("CountryID", models.AutoField(primary_key=True, serialize=False)),
                ("CountryName", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("TagID", models.AutoField(primary_key=True, serialize=False)),
                ("TagName", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("PostID", models.AutoField(primary_key=True, serialize=False)),
                ("Picture", models.ImageField(upload_to="")),
                ("Title", models.CharField(default="Post Title", max_length=100)),
                ("Text", models.CharField(max_length=10000)),
                ("Upvotes", models.IntegerField(default=0)),
                ("Downvotes", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "CountryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="rendezvous_app.country",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="downvoted_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="upvoted_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Tags",
                    models.ManyToManyField(
                        related_name="posts", to="rendezvous_app.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("CommentID", models.AutoField(primary_key=True, serialize=False)),
                ("Content", models.CharField(max_length=280)),
                ("Upvotes", models.IntegerField(default=0)),
                ("Downvotes", models.IntegerField(default=0)),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="downvoted_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="upvoted_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "PostID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="rendezvous_app.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Picture", models.ImageField(blank=True, upload_to="profile_images")),
                ("Bio", models.CharField(max_length=500)),
                (
                    "BornInCountryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="born_users",
                        to="rendezvous_app.country",
                    ),
                ),
                (
                    "LivingInCountryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living_users",
                        to="rendezvous_app.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
