# Generated by Django 5.0.3 on 2024-03-16 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
    ]
