# Generated by Django 5.0.3 on 2024-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="Downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="Upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
