# Generated by Django 5.0.3 on 2024-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0002_alter_country_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="PostID",
        ),
    ]
