# Generated by Django 5.0.3 on 2024-03-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0003_remove_post_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="Upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
