# Generated by Django 5.0.3 on 2024-03-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0005_alter_comment_userid_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="PostID",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
