# Generated by Django 5.0.3 on 2024-03-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0006_post_postid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="UserID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="rendezvous_app.profile",
            ),
            preserve_default=False,
        ),
    ]
