# Generated by Django 5.0.3 on 2024-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rendezvous_app", "0008_alter_post_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Title",
            field=models.CharField(default="Post Title", max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="Text",
            field=models.CharField(max_length=10000),
        ),
    ]
